### PR TITLE
Improve AVX2 hash speed.

### PR DESCRIPTION
**Pull request by klauspost**
Toyed a bit around and it seems like the biggest change came from loading the key value directly into the XOR.

Maybe an AMD specific optimization.

```
BenchmarkFixed128/241-AVX2-32           87.3          20.1          -76.98%
BenchmarkFixed128/512-AVX2-32           94.8          22.9          -75.82%
BenchmarkFixed128/1024-AVX2-32          104           30.1          -71.11%
BenchmarkFixed128/8192-AVX2-32          219           138           -36.97%
BenchmarkFixed128/102400-AVX2-32        1833          1562          -14.78%
BenchmarkFixed128/1024000-AVX2-32       18288         16166         -11.60%
BenchmarkFixed128/10240000-AVX2-32      191503        165534        -13.56%
BenchmarkFixed128/102400000-AVX2-32     5007156       4204041       -16.04%
BenchmarkFixed128/241-AVX2-32           2760.94      11996.27     4.34x
BenchmarkFixed128/512-AVX2-32           5403.02      22350.38     4.14x
BenchmarkFixed128/1024-AVX2-32          9844.49      34081.01     3.46x
BenchmarkFixed128/8192-AVX2-32          37382.01     59318.68     1.59x
BenchmarkFixed128/102400-AVX2-32        55875.41     65556.58     1.17x
BenchmarkFixed128/1024000-AVX2-32       55991.65     63343.83     1.13x
BenchmarkFixed128/10240000-AVX2-32      53471.70     61860.32     1.16x
BenchmarkFixed128/102400000-AVX2-32     20450.73     24357.52     1.19x 
```

cpu: AMD Ryzen 9 3950X 16-Core Processor

Moved the generation into the avo folder, since I couldn't make the other work.

### CODE REVIEW

**Comment by klauspost** [comment]
> apparently, throughput is better when it's lower 

Yeah, that's how I read it as well. 

> I don't know why the loop version runs faster when the unrolled version gets slower, though. I'll play around with some different orderings.

This is the first that moves beyond L1 size, so maybe some prefetching isn't that optimal on the Intel.

I had suspected that for any superscalar CPU the rolled/unrolled would be the same, but was surprised when it wasn't.

**Comment by klauspost** [comment]
@zeebo Tweaked some more stuff after rebasing. Experimented a bit. Found that for once prefetching was faster.

`VZEROUPPER` was missing. Huge improvement on small payloads.

Top benchmark updated.

**Comment by zeebo** [comment]
I saw your comment in the gophers slack to remember to add `VZEROUPPER`, so I went and did that without first seeing this PR. :smile: 

So I rebased and fixed the conflict. This is great! I also saw improvements on the order of ~12% for the 100K payloads. Thanks!

**Comment by klauspost** [comment]
@zeebo I saw you <3 there, so I assumed you had seen the PR already :D

Great it improves Intel as well 👍🏼

**Pull request merged**
